### PR TITLE
Add a cross-platform build script

### PR DESCRIPTION
**Pull request by cycomachead**
Use the macBuild John wrote and add a conditional to check the OS for stat.

Note to macOS users: You need a newer bash; use `brew install bash` to fix that.

### CODE REVIEW

**Comment by bromagosa** [comment]
Hmm... did you test this in a Linux box? It seems to be broken.

```
file: invalid option -- 'I'
Usage: file [-bcEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]
iconv: conversion from `-t' is not supported
Try `iconv --help' or `iconv --usage' for more information.
```

Wasn't the old `iconv` line working in MacOS? I'll revert to that if so. Otherwise we'll have to find compatible command line args for both `file` and `iconv`, which may not exist.

The other option is to just `if` the whole thing and run different commands for different OSes. I guess that's the easiest and safest way. Let me try that :)

**Comment by bromagosa** [comment]
The `sed -e '/@content/ {' -e 'r tmp.html' -e 'd' -e '}' -i "" $html` seems to not be cross-platform compatible either. Sigh.

**Comment by bromagosa** [comment]
Done :)

**Comment by cycomachead** [comment]
I ran the build on the staging server but I guess didn’t try watch. I looked up the arguments and they seemed like they should have been compatible. :/

Thanks for fixing that!

-- 
Michael Ball
From my iPhone
michaelball.co

**Pull request merged**
